import type { BrowseRoute, MapMode, MapZone, NodeType } from "../types/graph";

export const NODE_COLORS: Record<NodeType, number> = {
  band: 0xbd7049,
  guitarist: 0xd6b85d,
  artist: 0xc78a63,
  guitar: 0x7fa6d9,
  guitar_brand: 0xa78b68,
  genre: 0x5caaa2,
};

export const NODE_LABELS: Record<NodeType, string> = {
  band: "Band",
  guitarist: "Guitarist",
  artist: "Artist",
  guitar: "Guitar",
  guitar_brand: "Guitar brand",
  genre: "Genre",
};

export const MODE_LABELS: Record<MapMode, string> = {
  artists: "Artists",
  guitars: "Guitars",
};

export const MODE_TYPES: Record<MapMode, Set<NodeType>> = {
  artists: new Set(["band", "guitarist", "artist", "genre"]),
  guitars: new Set(["guitar", "guitar_brand", "genre"]),
};

export const MAP_ZONES: MapZone[] = [
  {
    id: "roots-blues",
    label: "ROOTS / BLUES",
    mode: "artists",
    x: -1360,
    y: -390,
    width: 760,
    height: 820,
    color: 0x5caaa2,
  },
  {
    id: "rock-circuit",
    label: "ROCK CIRCUIT",
    mode: "artists",
    x: -590,
    y: -370,
    width: 780,
    height: 610,
    color: 0xb79a47,
  },
  {
    id: "psychedelia-prog",
    label: "PSYCHEDELIA / PROG",
    mode: "artists",
    x: -540,
    y: -940,
    width: 1170,
    height: 520,
    color: 0x6f91b8,
  },
  {
    id: "hard-rock-metal",
    label: "HARD ROCK / METAL",
    mode: "artists",
    x: 250,
    y: -490,
    width: 980,
    height: 1540,
    color: 0xb0653d,
  },
  {
    id: "folk-country-vise",
    label: "FOLK / COUNTRY / VISE",
    mode: "artists",
    x: -1370,
    y: 450,
    width: 1770,
    height: 850,
    color: 0x83a66b,
  },
  {
    id: "guitar-workshop",
    label: "GUITAR WORKSHOP",
    mode: "guitars",
    x: 590,
    y: -930,
    width: 1160,
    height: 2280,
    color: 0x7fa6d9,
  },
  {
    id: "guitar-genres",
    label: "MUSICAL CONTEXT",
    mode: "guitars",
    x: -1350,
    y: -850,
    width: 1550,
    height: 2050,
    color: 0x5caaa2,
  },
];

export const BROWSE_ROUTES: BrowseRoute[] = [
  {
    id: "blues-to-rock",
    name: "Blues to rock",
    description: "Follow the amplified line from blues into rock and heavy music.",
    mode: "artists",
    color: 0x5caaa2,
    nodeIds: [
      "blues",
      "electric-blues",
      "bb-king",
      "chuck-berry",
      "rock-and-roll",
      "rock",
      "jimi-hendrix",
      "led-zeppelin",
      "heavy-metal",
    ],
  },
  {
    id: "british-guitar-line",
    name: "British guitar line",
    description: "A path through major British bands and guitar voices.",
    mode: "artists",
    color: 0xb79a47,
    nodeIds: [
      "the-yardbirds",
      "eric-clapton",
      "cream",
      "led-zeppelin",
      "jimmy-page",
      "pink-floyd",
      "david-gilmour",
      "dire-straits",
      "mark-knopfler",
    ],
  },
  {
    id: "yardbirds-branch",
    name: "Yardbirds branch",
    description: "One band as a switchboard for British blues-rock guitar.",
    mode: "artists",
    color: 0xb79a47,
    nodeIds: [
      "blues-rock",
      "the-yardbirds",
      "eric-clapton",
      "jeff-beck",
      "jimmy-page",
      "led-zeppelin",
    ],
  },
  {
    id: "prog-architecture",
    name: "Prog architecture",
    description: "Follow art rock into progressive guitar structures.",
    mode: "artists",
    color: 0x6f91b8,
    nodeIds: [
      "art-rock",
      "king-crimson",
      "robert-fripp",
      "progressive-rock",
      "yes",
      "steve-howe",
      "rush",
      "alex-lifeson",
      "pink-floyd",
      "david-gilmour",
    ],
  },
  {
    id: "norwegian-acoustic",
    name: "Norwegian acoustic corner",
    description: "Songcraft, humour and acoustic guitar traditions.",
    mode: "artists",
    color: 0x83a66b,
    nodeIds: [
      "folk",
      "norwegian-vise",
      "alf-cranner",
      "oystein-sunde",
      "gitarkameratene",
      "lillebjorn-nilsen",
      "jan-eggum",
      "halvdan-sivertsen",
    ],
  },
  {
    id: "heavy-route",
    name: "The heavy route",
    description: "Riffs, weight and the route into modern metal.",
    mode: "artists",
    color: 0xb0653d,
    nodeIds: [
      "hard-rock",
      "led-zeppelin",
      "black-sabbath",
      "tony-iommi",
      "heavy-metal",
      "judas-priest",
      "iron-maiden",
      "thrash-metal",
      "metallica",
      "james-hetfield",
      "megadeth",
      "dave-mustaine",
    ],
  },
  {
    id: "southern-slide",
    name: "Southern slide",
    description: "Blues-rock, twin guitars and Southern improvisation.",
    mode: "artists",
    color: 0x83a66b,
    nodeIds: [
      "blues-rock",
      "southern-rock",
      "allman-brothers-band",
      "duane-allman",
      "dickey-betts",
      "derek-trucks",
      "gibson-sg",
    ],
  },
  {
    id: "stratocaster-trail",
    name: "Stratocaster trail",
    description: "The guitar and several players who reshaped its voice.",
    mode: "guitars",
    color: 0x7fa6d9,
    nodeIds: ["fender", "fender-stratocaster"],
  },
  {
    id: "classic-gibson-line",
    name: "Classic Gibson line",
    description: "A short route through the brand's best-known electric shapes.",
    mode: "guitars",
    color: 0xa78b68,
    nodeIds: ["gibson", "gibson-les-paul", "gibson-sg", "gibson-flying-v"],
  },
  {
    id: "semi-hollow-thread",
    name: "Semi-hollow thread",
    description: "Blues, jazz and rock through warm electric bodies.",
    mode: "guitars",
    color: 0xbd7049,
    nodeIds: [
      "gibson",
      "gibson-es-335",
      "gibson-es-355-lucille",
      "electric-blues",
      "blues-rock",
      "jazz",
    ],
  },
  {
    id: "superstrat-route",
    name: "Superstrat route",
    description: "Hot-rodded guitars into virtuoso and metal design.",
    mode: "guitars",
    color: 0x7fa6d9,
    nodeIds: [
      "charvel",
      "charvel-san-dimas",
      "frankenstrat",
      "music-man-axis",
      "ibanez",
      "ibanez-rg",
      "ibanez-jem",
      "jackson",
      "jackson-soloist",
    ],
  },
  {
    id: "acoustic-history",
    name: "Acoustic history",
    description: "Dreadnoughts, stage instruments and country associations.",
    mode: "guitars",
    color: 0xd6b85d,
    nodeIds: ["martin", "martin-d28", "gibson", "gibson-j45", "trigger"],
  },
];

export function modeForType(type: NodeType): MapMode {
  return type === "guitar" || type === "guitar_brand" ? "guitars" : "artists";
}

export function colorToCss(color: number): string {
  return `#${color.toString(16).padStart(6, "0")}`;
}
