(function () {
  const wikipedia = (slug) => ({
    label: "Wikipedia",
    url: `https://en.wikipedia.org/wiki/${slug}`,
  });

  const nowiki = (slug) => ({
    label: "Wikipedia",
    url: `https://no.wikipedia.org/wiki/${slug}`,
  });

  window.GUITAR_GRAPH_DATA = {
    nodes: [
      {
        id: "blues",
        label: "Blues",
        type: "genre",
        x: -740,
        y: 120,
        size: 22,
        starter: true,
        summary: "A root system for much of modern guitar music, built around call and response, bent notes, shuffle feel and personal storytelling.",
        meta: ["Genre", "Roots music"],
        sources: [wikipedia("Blues")],
      },
      {
        id: "electric-blues",
        label: "Electric blues",
        type: "genre",
        x: -560,
        y: 40,
        size: 20,
        starter: true,
        summary: "Blues amplified for clubs, cities and louder bands. It shaped rock guitar tone, soloing and the idea of the electric guitar as a lead voice.",
        meta: ["Genre", "Amplified blues"],
        sources: [wikipedia("Electric_blues")],
      },
      {
        id: "rock-and-roll",
        label: "Rock and roll",
        type: "genre",
        x: -390,
        y: -120,
        size: 20,
        summary: "A high-energy meeting point between blues, country, gospel and rhythm and blues, with the guitar pushed toward the front.",
        meta: ["Genre", "1950s"],
        sources: [wikipedia("Rock_and_roll")],
      },
      {
        id: "rock",
        label: "Rock",
        type: "genre",
        x: -130,
        y: -40,
        size: 24,
        starter: true,
        summary: "The broad guitar-centered field that branches into psychedelic rock, progressive rock, hard rock, metal, punk and grunge.",
        meta: ["Genre", "Guitar culture"],
        sources: [wikipedia("Rock_music")],
      },
      {
        id: "psychedelic-rock",
        label: "Psychedelic rock",
        type: "genre",
        x: -120,
        y: -340,
        size: 18,
        summary: "A late-1960s rock branch marked by effects, improvisation, studio experimentation and expanded guitar textures.",
        meta: ["Genre", "1960s"],
        sources: [wikipedia("Psychedelic_rock")],
      },
      {
        id: "progressive-rock",
        label: "Progressive rock",
        type: "genre",
        x: 260,
        y: -330,
        size: 19,
        starter: true,
        summary: "Rock music stretched toward longer forms, concept albums, unusual harmony and more cinematic guitar arrangements.",
        meta: ["Genre", "Album era"],
        sources: [wikipedia("Progressive_rock")],
      },
      {
        id: "hard-rock",
        label: "Hard rock",
        type: "genre",
        x: 250,
        y: 20,
        size: 21,
        summary: "Louder blues-rock DNA with heavier riffs, thicker amps and an arena-sized guitar sound.",
        meta: ["Genre", "Amplified rock"],
        sources: [wikipedia("Hard_rock")],
      },
      {
        id: "heavy-metal",
        label: "Heavy metal",
        type: "genre",
        x: 620,
        y: 160,
        size: 22,
        starter: true,
        summary: "A heavier guitar tradition built around riffs, distortion, volume and darker harmonic colors.",
        meta: ["Genre", "Riff culture"],
        sources: [wikipedia("Heavy_metal_music")],
      },
      {
        id: "punk",
        label: "Punk rock",
        type: "genre",
        x: 240,
        y: 520,
        size: 17,
        summary: "Direct, sharp and often minimal guitar music that reacted against excess and pushed attitude to the front.",
        meta: ["Genre", "1970s"],
        sources: [wikipedia("Punk_rock")],
      },
      {
        id: "grunge",
        label: "Grunge",
        type: "genre",
        x: 520,
        y: 640,
        size: 18,
        starter: true,
        summary: "A rough-edged Seattle-centered rock movement where punk urgency met heavy guitar weight and melodic songwriting.",
        meta: ["Genre", "1990s"],
        sources: [wikipedia("Grunge")],
      },
      {
        id: "folk",
        label: "Folk",
        type: "genre",
        x: -620,
        y: 620,
        size: 20,
        starter: true,
        summary: "Song-centered acoustic traditions where the guitar often works as both rhythm instrument and storytelling companion.",
        meta: ["Genre", "Acoustic tradition"],
        sources: [wikipedia("Folk_music")],
      },
      {
        id: "country",
        label: "Country",
        type: "genre",
        x: -860,
        y: 520,
        size: 18,
        summary: "American roots music with strong acoustic, electric and fingerstyle guitar traditions.",
        meta: ["Genre", "Roots music"],
        sources: [wikipedia("Country_music")],
      },
      {
        id: "norwegian-vise",
        label: "Norwegian vise",
        type: "genre",
        x: -300,
        y: 800,
        size: 17,
        summary: "A Nordic song tradition where lyric, humor, melody and acoustic instruments often carry equal weight.",
        meta: ["Genre", "Norwegian song"],
        sources: [wikipedia("Vise")],
      },
      {
        id: "funk",
        label: "Funk",
        type: "genre",
        x: -20,
        y: 310,
        size: 18,
        summary: "Rhythm-first music where guitar often becomes a clipped, syncopated engine inside the groove.",
        meta: ["Genre", "Rhythm guitar"],
        sources: [wikipedia("Funk")],
      },
      {
        id: "jazz-fusion",
        label: "Jazz fusion",
        type: "genre",
        x: -70,
        y: 500,
        size: 17,
        summary: "A meeting of jazz harmony, rock volume, funk rhythm and expanded improvisation.",
        meta: ["Genre", "Hybrid form"],
        sources: [wikipedia("Jazz_fusion")],
      },
      {
        id: "bb-king",
        label: "B.B. King",
        type: "artist",
        x: -760,
        y: -120,
        size: 24,
        starter: true,
        summary: "One of electric blues' defining guitar voices, known for vocal phrasing, controlled vibrato and his Gibson-based Lucille guitars.",
        meta: ["Guitarist", "Singer", "Electric blues"],
        sources: [wikipedia("B.B._King")],
      },
      {
        id: "lead-belly",
        label: "Lead Belly",
        type: "artist",
        x: -980,
        y: 210,
        size: 19,
        summary: "A major folk and blues figure whose repertoire and twelve-string guitar style fed later folk, blues and rock musicians.",
        meta: ["Singer", "Guitarist", "Twelve-string"],
        sources: [wikipedia("Lead_Belly")],
      },
      {
        id: "chuck-berry",
        label: "Chuck Berry",
        type: "artist",
        x: -520,
        y: -260,
        size: 22,
        starter: true,
        summary: "A foundational rock and roll guitarist and songwriter whose riffs, double-stops and showmanship became a rock grammar.",
        meta: ["Guitarist", "Songwriter", "Rock and roll"],
        sources: [wikipedia("Chuck_Berry")],
      },
      {
        id: "elvis-presley",
        label: "Elvis Presley",
        type: "artist",
        x: -280,
        y: -290,
        size: 20,
        summary: "A rock and roll catalyst who helped bring country, blues and rhythm and blues language into mass popular culture.",
        meta: ["Singer", "Rock and roll"],
        sources: [wikipedia("Elvis_Presley")],
      },
      {
        id: "jimi-hendrix",
        label: "Jimi Hendrix",
        type: "artist",
        x: -240,
        y: -500,
        size: 28,
        starter: true,
        summary: "A transformative electric guitarist who expanded feedback, fuzz, wah, chord melody and studio sound into a new rock language.",
        meta: ["Guitarist", "Singer", "Psychedelic rock"],
        sources: [wikipedia("Jimi_Hendrix")],
      },
      {
        id: "stevie-ray-vaughan",
        label: "Stevie Ray Vaughan",
        type: "artist",
        x: -520,
        y: -430,
        size: 22,
        starter: true,
        summary: "A Texas blues-rock guitarist who revived electric blues guitar for a new generation with huge Stratocaster tone and fierce phrasing.",
        meta: ["Guitarist", "Singer", "Blues rock"],
        sources: [wikipedia("Stevie_Ray_Vaughan")],
      },
      {
        id: "eric-clapton",
        label: "Eric Clapton",
        type: "artist",
        x: -120,
        y: -160,
        size: 21,
        summary: "A blues-rock guitarist linked to the Yardbirds, Cream and a long solo career across electric blues, rock and pop.",
        meta: ["Guitarist", "Singer", "Blues rock"],
        sources: [wikipedia("Eric_Clapton")],
      },
      {
        id: "david-gilmour",
        label: "David Gilmour",
        type: "artist",
        x: 210,
        y: -530,
        size: 23,
        starter: true,
        summary: "Pink Floyd's lead guitarist and singer, known for melodic bends, spacious tone and cinematic solo construction.",
        meta: ["Guitarist", "Singer", "Progressive rock"],
        sources: [wikipedia("David_Gilmour")],
      },
      {
        id: "mark-knopfler",
        label: "Mark Knopfler",
        type: "artist",
        x: -340,
        y: 240,
        size: 22,
        starter: true,
        summary: "Dire Straits' guitarist and songwriter, recognized for clean fingerstyle electric playing and economical melodic phrasing.",
        meta: ["Guitarist", "Songwriter", "Fingerstyle"],
        sources: [wikipedia("Mark_Knopfler")],
      },
      {
        id: "eddie-van-halen",
        label: "Eddie Van Halen",
        type: "artist",
        x: 360,
        y: -80,
        size: 25,
        starter: true,
        summary: "A technical and sonic innovator whose tapping, harmonics, tremolo work and self-built guitar pushed hard rock guitar forward.",
        meta: ["Guitarist", "Inventive gear"],
        sources: [wikipedia("Eddie_Van_Halen")],
      },
      {
        id: "frank-zappa",
        label: "Frank Zappa",
        type: "artist",
        x: -10,
        y: 620,
        size: 20,
        summary: "A composer, bandleader and guitarist who connected rock, jazz fusion, satire and complex arrangement.",
        meta: ["Guitarist", "Composer", "Bandleader"],
        sources: [wikipedia("Frank_Zappa")],
      },
      {
        id: "johnny-marr",
        label: "Johnny Marr",
        type: "artist",
        x: 90,
        y: 420,
        size: 20,
        summary: "The Smiths' guitarist, known for layered arpeggios, bright rhythm parts and a melodic alternative-rock vocabulary.",
        meta: ["Guitarist", "Alternative rock"],
        sources: [wikipedia("Johnny_Marr")],
      },
      {
        id: "randy-rhoads",
        label: "Randy Rhoads",
        type: "artist",
        x: 720,
        y: -60,
        size: 21,
        summary: "A neoclassical-leaning metal guitarist whose work with Ozzy Osbourne made precision and classical influence central to heavy guitar.",
        meta: ["Guitarist", "Heavy metal"],
        sources: [wikipedia("Randy_Rhoads")],
      },
      {
        id: "tony-iommi",
        label: "Tony Iommi",
        type: "artist",
        x: 780,
        y: 230,
        size: 23,
        starter: true,
        summary: "Black Sabbath's guitarist and a core architect of heavy metal riffing, with dark tuning choices and massive SG-driven tone.",
        meta: ["Guitarist", "Riff writer", "Heavy metal"],
        sources: [wikipedia("Tony_Iommi")],
      },
      {
        id: "jimmy-page",
        label: "Jimmy Page",
        type: "artist",
        x: 230,
        y: -130,
        size: 23,
        starter: true,
        summary: "Led Zeppelin's guitarist and producer, central to hard rock through riffs, acoustic textures, studio craft and blues reinvention.",
        meta: ["Guitarist", "Producer", "Hard rock"],
        sources: [wikipedia("Jimmy_Page")],
      },
      {
        id: "george-harrison",
        label: "George Harrison",
        type: "artist",
        x: -50,
        y: -690,
        size: 20,
        summary: "The Beatles' lead guitarist, whose melodic parts, twelve-string sounds and Indian music interests broadened rock guitar color.",
        meta: ["Guitarist", "Songwriter", "The Beatles"],
        sources: [wikipedia("George_Harrison")],
      },
      {
        id: "bob-dylan",
        label: "Bob Dylan",
        type: "artist",
        x: -700,
        y: 760,
        size: 22,
        starter: true,
        summary: "A songwriter who linked folk, blues, rock and electric controversy, reshaping what guitar-led songwriting could carry.",
        meta: ["Songwriter", "Folk", "Rock"],
        sources: [wikipedia("Bob_Dylan")],
      },
      {
        id: "johnny-cash",
        label: "Johnny Cash",
        type: "artist",
        x: -1040,
        y: 640,
        size: 20,
        summary: "A country figure whose spare rhythm guitar, voice and storytelling style became instantly recognizable.",
        meta: ["Singer", "Country", "Rhythm guitar"],
        sources: [wikipedia("Johnny_Cash")],
      },
      {
        id: "willie-nelson",
        label: "Willie Nelson",
        type: "artist",
        x: -890,
        y: 820,
        size: 20,
        starter: true,
        summary: "A country songwriter and guitarist whose nylon-string guitar Trigger became part of his musical identity.",
        meta: ["Singer", "Songwriter", "Trigger"],
        sources: [wikipedia("Willie_Nelson")],
      },
      {
        id: "chet-atkins",
        label: "Chet Atkins",
        type: "artist",
        x: -1050,
        y: 430,
        size: 20,
        summary: "A country guitar master and producer whose fingerstyle approach shaped Nashville guitar vocabulary.",
        meta: ["Guitarist", "Producer", "Fingerstyle"],
        sources: [wikipedia("Chet_Atkins")],
      },
      {
        id: "john-mayer",
        label: "John Mayer",
        type: "artist",
        x: -420,
        y: -610,
        size: 18,
        summary: "A modern guitarist and songwriter who draws a clear line from blues guitar vocabulary into pop, soul and jam settings.",
        meta: ["Guitarist", "Singer", "Modern blues"],
        sources: [wikipedia("John_Mayer")],
      },
      {
        id: "oystein-sunde",
        label: "Øystein Sunde",
        type: "artist",
        x: -160,
        y: 880,
        size: 22,
        starter: true,
        summary: "A Norwegian singer-songwriter and guitarist known for fast wordplay, humor, acoustic precision and links to Gitarkameratene.",
        meta: ["Guitarist", "Banjo", "Norwegian vise"],
        sources: [wikipedia("%C3%98ystein_Sunde"), nowiki("%C3%98ystein_Sunde")],
      },
      {
        id: "james-hetfield",
        label: "James Hetfield",
        type: "artist",
        x: 900,
        y: 470,
        size: 21,
        summary: "Metallica's rhythm guitarist and vocalist, known for tight downpicking and precise heavy-metal rhythm architecture.",
        meta: ["Rhythm guitar", "Vocalist", "Heavy metal"],
        sources: [wikipedia("James_Hetfield")],
      },
      {
        id: "prince",
        label: "Prince",
        type: "artist",
        x: 130,
        y: 260,
        size: 22,
        starter: true,
        summary: "A multi-instrumentalist whose guitar work fused funk, rock, pop and soul with theatrical precision and explosive solos.",
        meta: ["Guitarist", "Songwriter", "Funk"],
        sources: [wikipedia("Prince_(musician)")],
      },
      {
        id: "the-beatles",
        label: "The Beatles",
        type: "band",
        x: -20,
        y: -560,
        size: 25,
        starter: true,
        summary: "A central 1960s band whose songwriting, studio practice and guitar textures reshaped pop and rock music.",
        meta: ["Band", "1960s", "Rock"],
        sources: [wikipedia("The_Beatles")],
      },
      {
        id: "pink-floyd",
        label: "Pink Floyd",
        type: "band",
        x: 380,
        y: -480,
        size: 24,
        starter: true,
        summary: "A psychedelic and progressive rock band built around atmosphere, albums, sound design and David Gilmour's melodic guitar.",
        meta: ["Band", "Progressive rock"],
        sources: [wikipedia("Pink_Floyd")],
      },
      {
        id: "led-zeppelin",
        label: "Led Zeppelin",
        type: "band",
        x: 420,
        y: -170,
        size: 25,
        starter: true,
        summary: "A hard rock band that fused blues, folk, riffs and studio ambition into a huge guitar-centered sound.",
        meta: ["Band", "Hard rock"],
        sources: [wikipedia("Led_Zeppelin")],
      },
      {
        id: "black-sabbath",
        label: "Black Sabbath",
        type: "band",
        x: 940,
        y: 250,
        size: 25,
        starter: true,
        summary: "A Birmingham band whose dark riffs, volume and atmosphere became a foundation for heavy metal.",
        meta: ["Band", "Heavy metal"],
        sources: [wikipedia("Black_Sabbath")],
      },
      {
        id: "van-halen",
        label: "Van Halen",
        type: "band",
        x: 520,
        y: -190,
        size: 22,
        summary: "A Los Angeles hard rock band that made Eddie Van Halen's guitar innovations part of mainstream rock language.",
        meta: ["Band", "Hard rock"],
        sources: [wikipedia("Van_Halen")],
      },
      {
        id: "dire-straits",
        label: "Dire Straits",
        type: "band",
        x: -180,
        y: 190,
        size: 21,
        summary: "A British band centered on Mark Knopfler's clean fingerstyle electric guitar and narrative songwriting.",
        meta: ["Band", "Rock"],
        sources: [wikipedia("Dire_Straits")],
      },
      {
        id: "the-smiths",
        label: "The Smiths",
        type: "band",
        x: 230,
        y: 430,
        size: 20,
        summary: "An alternative rock band where Johnny Marr's layered guitars became as defining as the vocals and lyrics.",
        meta: ["Band", "Alternative rock"],
        sources: [wikipedia("The_Smiths")],
      },
      {
        id: "ozzy-osbourne",
        label: "Ozzy Osbourne",
        type: "band",
        x: 870,
        y: -60,
        size: 19,
        summary: "Ozzy's solo band platform gave Randy Rhoads a major stage for neoclassical metal guitar.",
        meta: ["Solo artist", "Band context"],
        sources: [wikipedia("Ozzy_Osbourne")],
      },
      {
        id: "metallica",
        label: "Metallica",
        type: "band",
        x: 1050,
        y: 470,
        size: 24,
        starter: true,
        summary: "A heavy metal band where tight rhythm guitar, palm muting and aggressive arrangement became genre-defining.",
        meta: ["Band", "Heavy metal"],
        sources: [wikipedia("Metallica")],
      },
      {
        id: "gitarkameratene",
        label: "Gitarkameratene",
        type: "band",
        x: 60,
        y: 820,
        size: 19,
        summary: "A Norwegian guitar and vocal group linking Øystein Sunde with other major Norwegian songwriters and performers.",
        meta: ["Group", "Norwegian song"],
        sources: [nowiki("Gitarkameratene")],
      },
      {
        id: "cream",
        label: "Cream",
        type: "band",
        x: -20,
        y: -250,
        size: 18,
        summary: "A blues-rock trio that helped push louder improvisational rock guitar into the late 1960s.",
        meta: ["Band", "Blues rock"],
        sources: [wikipedia("Cream_(band)")],
      },
      {
        id: "the-yardbirds",
        label: "The Yardbirds",
        type: "band",
        x: -210,
        y: -260,
        size: 18,
        summary: "A British blues-rock band famously connected to Eric Clapton, Jeff Beck and Jimmy Page.",
        meta: ["Band", "British blues"],
        sources: [wikipedia("The_Yardbirds")],
      },
      {
        id: "fender",
        label: "Fender",
        type: "maker",
        x: 1220,
        y: -240,
        size: 22,
        starter: true,
        summary: "A manufacturer central to electric guitar history through solid-body designs, amplifiers and working-musician instruments.",
        meta: ["Maker", "Electric guitars"],
        sources: [wikipedia("Fender_Musical_Instruments_Corporation")],
      },
      {
        id: "gibson",
        label: "Gibson",
        type: "maker",
        x: 1530,
        y: 60,
        size: 22,
        starter: true,
        summary: "A historic maker tied to archtops, Les Pauls, SGs, semi-hollow guitars and many blues, rock and metal players.",
        meta: ["Maker", "Electric and acoustic guitars"],
        sources: [wikipedia("Gibson_(guitar_company)")],
      },
      {
        id: "martin",
        label: "C.F. Martin & Co.",
        type: "maker",
        x: 1230,
        y: 720,
        size: 20,
        starter: true,
        summary: "A major acoustic guitar maker whose dreadnought designs are deeply tied to folk, country and singer-songwriter traditions.",
        meta: ["Maker", "Acoustic guitars"],
        sources: [wikipedia("C._F._Martin_%26_Company")],
      },
      {
        id: "rickenbacker",
        label: "Rickenbacker",
        type: "maker",
        x: 1120,
        y: -590,
        size: 18,
        summary: "A maker strongly associated with jangly electric twelve-string sounds in 1960s rock and later alternative music.",
        meta: ["Maker", "Twelve-string electric"],
        sources: [wikipedia("Rickenbacker")],
      },
      {
        id: "gretsch",
        label: "Gretsch",
        type: "maker",
        x: 1050,
        y: 360,
        size: 18,
        summary: "A maker associated with hollow-body electrics, country, rockabilly and distinctive filtered pickup tones.",
        meta: ["Maker", "Hollow-body electric"],
        sources: [wikipedia("Gretsch")],
      },
      {
        id: "esp",
        label: "ESP",
        type: "maker",
        x: 1480,
        y: 510,
        size: 18,
        summary: "A guitar maker closely associated with modern metal, custom shop instruments and high-output rock designs.",
        meta: ["Maker", "Metal guitars"],
        sources: [wikipedia("ESP_Guitars")],
      },
      {
        id: "fender-stratocaster",
        label: "Fender Stratocaster",
        type: "guitar",
        x: 1040,
        y: -120,
        size: 24,
        starter: true,
        summary: "A contoured solid-body electric with three pickups and tremolo system, tied to Hendrix, Vaughan, Gilmour, Knopfler and many others.",
        meta: ["Guitar", "1954", "Solid-body"],
        sources: [wikipedia("Fender_Stratocaster")],
      },
      {
        id: "fender-telecaster",
        label: "Fender Telecaster",
        type: "guitar",
        x: 1050,
        y: 120,
        size: 21,
        starter: true,
        summary: "A simple slab-bodied solid electric known for bright attack, durability and a long life across country, rock and funk.",
        meta: ["Guitar", "1950s", "Solid-body"],
        sources: [wikipedia("Fender_Telecaster")],
      },
      {
        id: "fender-jaguar",
        label: "Fender Jaguar",
        type: "guitar",
        x: 1060,
        y: 610,
        size: 18,
        summary: "An offset Fender model that found a second life in punk, alternative rock and grunge scenes.",
        meta: ["Guitar", "Offset", "Alternative rock"],
        sources: [wikipedia("Fender_Jaguar")],
      },
      {
        id: "fender-jazzmaster",
        label: "Fender Jazzmaster",
        type: "guitar",
        x: 930,
        y: 500,
        size: 18,
        summary: "An offset Fender guitar adopted by alternative and indie players for its wide single-coils and floating tremolo feel.",
        meta: ["Guitar", "Offset"],
        sources: [wikipedia("Fender_Jazzmaster")],
      },
      {
        id: "gibson-les-paul",
        label: "Gibson Les Paul",
        type: "guitar",
        x: 1360,
        y: 40,
        size: 24,
        starter: true,
        summary: "A carved-top solid-body electric strongly associated with sustain, humbuckers and blues-rock to hard-rock lead guitar.",
        meta: ["Guitar", "1952", "Solid-body"],
        sources: [wikipedia("Gibson_Les_Paul")],
      },
      {
        id: "gibson-sg",
        label: "Gibson SG",
        type: "guitar",
        x: 1420,
        y: 260,
        size: 21,
        starter: true,
        summary: "A lighter double-cutaway Gibson model that became iconic in hard rock and heavy metal through players like Tony Iommi.",
        meta: ["Guitar", "Double-cutaway"],
        sources: [wikipedia("Gibson_SG")],
      },
      {
        id: "gibson-es-355-lucille",
        label: "Gibson ES-355 Lucille",
        type: "guitar",
        x: 1320,
        y: -280,
        size: 22,
        starter: true,
        summary: "The Lucille line reflects B.B. King's signature semi-hollow guitar identity, connected to his singing electric blues tone.",
        meta: ["Guitar", "Semi-hollow", "Signature"],
        sources: [wikipedia("Lucille_(guitar)")],
      },
      {
        id: "gibson-flying-v",
        label: "Gibson Flying V",
        type: "guitar",
        x: 1670,
        y: 310,
        size: 19,
        summary: "A radical late-1950s Gibson shape later embraced by blues-rock and metal players for stage presence and sustain.",
        meta: ["Guitar", "1958", "Solid-body"],
        sources: [wikipedia("Gibson_Flying_V")],
      },
      {
        id: "martin-d28",
        label: "Martin D-28",
        type: "guitar",
        x: 1040,
        y: 790,
        size: 20,
        starter: true,
        summary: "A benchmark dreadnought acoustic associated with bluegrass, folk, country and singer-songwriter recording.",
        meta: ["Guitar", "Dreadnought", "Acoustic"],
        sources: [wikipedia("Martin_D-28")],
      },
      {
        id: "gibson-j45",
        label: "Gibson J-45",
        type: "guitar",
        x: 1420,
        y: 720,
        size: 18,
        summary: "A workhorse slope-shoulder acoustic linked to folk, country and singer-songwriter rhythm playing.",
        meta: ["Guitar", "Acoustic"],
        sources: [wikipedia("Gibson_J-45")],
      },
      {
        id: "trigger",
        label: "Trigger",
        type: "guitar",
        x: 1040,
        y: 930,
        size: 19,
        starter: true,
        summary: "Willie Nelson's heavily worn Martin N-20 nylon-string guitar, one of country music's most recognizable instruments.",
        meta: ["Guitar", "Martin N-20", "Signature instrument"],
        sources: [wikipedia("Trigger_(guitar)")],
      },
      {
        id: "rickenbacker-360-12",
        label: "Rickenbacker 360/12",
        type: "guitar",
        x: 900,
        y: -610,
        size: 19,
        starter: true,
        summary: "A twelve-string electric tied to jangly Beatles-era textures and later alternative guitar layers.",
        meta: ["Guitar", "Twelve-string electric"],
        sources: [wikipedia("Rickenbacker_360/12")],
      },
      {
        id: "gretsch-6120",
        label: "Gretsch 6120",
        type: "guitar",
        x: 900,
        y: 300,
        size: 18,
        summary: "A hollow-body electric strongly associated with Chet Atkins, Nashville tone and rockabilly lineage.",
        meta: ["Guitar", "Hollow-body"],
        sources: [wikipedia("Gretsch_6120")],
      },
      {
        id: "frankenstrat",
        label: "Frankenstrat",
        type: "guitar",
        x: 820,
        y: -160,
        size: 20,
        starter: true,
        summary: "Eddie Van Halen's self-built hybrid guitar, made to combine Strat-style feel with higher-output hard-rock power.",
        meta: ["Guitar", "Custom build", "Eddie Van Halen"],
        sources: [wikipedia("Frankenstrat")],
      },
      {
        id: "ibanez-jem",
        label: "Ibanez JEM",
        type: "guitar",
        x: 1740,
        y: -120,
        size: 18,
        summary: "A high-performance signature guitar associated with Steve Vai and the 1980s/1990s superstrat tradition.",
        meta: ["Guitar", "Superstrat", "Signature"],
        sources: [wikipedia("Ibanez_JEM")],
      },
      {
        id: "esp-explorer-style",
        label: "ESP Explorer style",
        type: "guitar",
        x: 1660,
        y: 530,
        size: 18,
        summary: "Explorer-style ESP instruments became part of the visual and rhythmic identity of modern heavy metal guitar.",
        meta: ["Guitar", "Metal", "Explorer shape"],
        sources: [wikipedia("ESP_Guitars")],
      },
      {
        id: "hohner-mad-cat",
        label: "Hohner Mad Cat",
        type: "guitar",
        x: 860,
        y: 120,
        size: 17,
        summary: "A Telecaster-inspired guitar closely associated with Prince's stage and studio sound.",
        meta: ["Guitar", "Prince", "Tele-style"],
        sources: [wikipedia("Prince_(musician)")],
      },
      {
        id: "banjo",
        label: "Banjo",
        type: "guitar",
        x: 360,
        y: 920,
        size: 17,
        summary: "A plucked string instrument that often crosses into folk, country, bluegrass and comic virtuoso performance contexts.",
        meta: ["Instrument", "Plucked strings"],
        sources: [wikipedia("Banjo")],
      },
      {
        id: "national-resonator",
        label: "National resonator",
        type: "guitar",
        x: 880,
        y: 850,
        size: 17,
        summary: "Resonator guitars project with a metal cone and became strongly linked to blues, slide and early acoustic volume needs.",
        meta: ["Guitar", "Resonator"],
        sources: [wikipedia("Resonator_guitar")],
      },
      {
        id: "are-you-experienced",
        label: "Are You Experienced",
        type: "release",
        x: -30,
        y: -820,
        size: 16,
        summary: "The debut album that introduced much of Hendrix's guitar vocabulary to a wide rock audience.",
        meta: ["Album", "1967"],
        sources: [wikipedia("Are_You_Experienced")],
      },
      {
        id: "texas-flood",
        label: "Texas Flood",
        type: "release",
        x: -700,
        y: -580,
        size: 16,
        summary: "Stevie Ray Vaughan and Double Trouble's debut, a key 1980s electric blues revival record.",
        meta: ["Album", "1983"],
        sources: [wikipedia("Texas_Flood")],
      },
      {
        id: "live-at-the-regal",
        label: "Live at the Regal",
        type: "release",
        x: -950,
        y: -230,
        size: 16,
        summary: "A landmark B.B. King live album often cited for electric blues phrasing, dynamics and audience connection.",
        meta: ["Live album", "1965"],
        sources: [wikipedia("Live_at_the_Regal")],
      },
      {
        id: "dark-side-of-the-moon",
        label: "The Dark Side of the Moon",
        type: "release",
        x: 540,
        y: -660,
        size: 17,
        summary: "A Pink Floyd album where guitar serves atmosphere, melody and album-scale architecture.",
        meta: ["Album", "1973"],
        sources: [wikipedia("The_Dark_Side_of_the_Moon")],
      },
      {
        id: "brothers-in-arms",
        label: "Brothers in Arms",
        type: "release",
        x: -170,
        y: 360,
        size: 16,
        summary: "A Dire Straits album that brought clean guitar tone, digital-era production and Knopfler's phrasing to a huge audience.",
        meta: ["Album", "1985"],
        sources: [wikipedia("Brothers_in_Arms_(album)")],
      },
      {
        id: "van-halen-i",
        label: "Van Halen",
        type: "release",
        x: 660,
        y: -300,
        size: 16,
        summary: "The debut album that made Eddie Van Halen's approach impossible to ignore.",
        meta: ["Album", "1978"],
        sources: [wikipedia("Van_Halen_(album)")],
      },
      {
        id: "sgt-pepper",
        label: "Sgt. Pepper",
        type: "release",
        x: 120,
        y: -820,
        size: 16,
        summary: "A Beatles studio landmark where guitar, arrangement and recording became part of a larger pop-art palette.",
        meta: ["Album", "1967"],
        sources: [wikipedia("Sgt._Pepper%27s_Lonely_Hearts_Club_Band")],
      },
      {
        id: "led-zeppelin-iv",
        label: "Led Zeppelin IV",
        type: "release",
        x: 580,
        y: -20,
        size: 16,
        summary: "A hard rock touchstone balancing riffs, folk acoustic color and huge guitar production.",
        meta: ["Album", "1971"],
        sources: [wikipedia("Led_Zeppelin_IV")],
      },
      {
        id: "paranoid",
        label: "Paranoid",
        type: "release",
        x: 1040,
        y: 130,
        size: 16,
        summary: "A Black Sabbath album that helped codify heavy metal riff language.",
        meta: ["Album", "1970"],
        sources: [wikipedia("Paranoid_(album)")],
      },
      {
        id: "master-of-reality",
        label: "Master of Reality",
        type: "release",
        x: 1080,
        y: 300,
        size: 16,
        summary: "A Black Sabbath album tied to heavier guitar tunings and riff density.",
        meta: ["Album", "1971"],
        sources: [wikipedia("Master_of_Reality")],
      },
      {
        id: "highway-61-revisited",
        label: "Highway 61 Revisited",
        type: "release",
        x: -560,
        y: 910,
        size: 16,
        summary: "A key electric-era Dylan album connecting folk songwriting to rock instrumentation.",
        meta: ["Album", "1965"],
        sources: [wikipedia("Highway_61_Revisited")],
      },
      {
        id: "at-folsom-prison",
        label: "At Folsom Prison",
        type: "release",
        x: -1170,
        y: 760,
        size: 16,
        summary: "A landmark Johnny Cash live album with stark rhythm, voice and storytelling at the center.",
        meta: ["Live album", "1968"],
        sources: [wikipedia("At_Folsom_Prison")],
      },
      {
        id: "kjekt-a-ha",
        label: "Kjekt å ha",
        type: "release",
        x: -40,
        y: 1040,
        size: 16,
        summary: "A well-known Øystein Sunde album title that fits his humorous, guitar-driven songwriting world.",
        meta: ["Album", "Norwegian song"],
        sources: [nowiki("Kjekt_%C3%A5_ha")],
      },
      {
        id: "fingerpicking",
        label: "Fingerpicking",
        type: "technique",
        x: -520,
        y: 430,
        size: 16,
        summary: "A right-hand approach where fingers pluck separate strings, central to folk, country, blues and many acoustic styles.",
        meta: ["Technique", "Right hand"],
        sources: [wikipedia("Fingerstyle_guitar")],
      },
      {
        id: "slide-guitar",
        label: "Slide guitar",
        type: "technique",
        x: -880,
        y: 30,
        size: 16,
        summary: "A technique using a slide to glide between pitches, deeply linked to blues and resonator guitar traditions.",
        meta: ["Technique", "Blues"],
        sources: [wikipedia("Slide_guitar")],
      },
      {
        id: "whammy-bar",
        label: "Whammy bar",
        type: "technique",
        x: 600,
        y: -420,
        size: 16,
        summary: "A tremolo arm technique used for pitch dips, flutters, dive bombs and expressive electric guitar effects.",
        meta: ["Technique", "Pitch movement"],
        sources: [wikipedia("Vibrato_systems_for_guitar")],
      },
      {
        id: "distortion",
        label: "Distortion",
        type: "technique",
        x: 540,
        y: 60,
        size: 17,
        summary: "Amplifier or pedal clipping that gives electric guitar sustain, grit and harmonic weight.",
        meta: ["Sound", "Electric guitar"],
        sources: [wikipedia("Distortion_(music)")],
      },
      {
        id: "twelve-string-sound",
        label: "Twelve-string sound",
        type: "technique",
        x: 720,
        y: -650,
        size: 16,
        summary: "A doubled-course shimmer heard in folk, 1960s pop-rock and later jangly alternative guitar textures.",
        meta: ["Sound", "Texture"],
        sources: [wikipedia("Twelve-string_guitar")],
      },
    ],
    edges: [
      { from: "blues", to: "electric-blues", label: "amplified into", strength: 0.88 },
      { from: "blues", to: "rock-and-roll", label: "feeds", strength: 0.72 },
      { from: "rock-and-roll", to: "rock", label: "branches into", strength: 0.82 },
      { from: "rock", to: "psychedelic-rock", label: "branches into", strength: 0.7 },
      { from: "rock", to: "progressive-rock", label: "branches into", strength: 0.68 },
      { from: "rock", to: "hard-rock", label: "branches into", strength: 0.8 },
      { from: "hard-rock", to: "heavy-metal", label: "heavier edge", strength: 0.86 },
      { from: "punk", to: "grunge", label: "roughens into", strength: 0.67 },
      { from: "rock", to: "punk", label: "reacts into", strength: 0.62 },
      { from: "folk", to: "country", label: "roots overlap", strength: 0.62 },
      { from: "folk", to: "norwegian-vise", label: "song tradition", strength: 0.7 },
      { from: "funk", to: "rock", label: "rhythmic crossover", strength: 0.45 },
      { from: "jazz-fusion", to: "funk", label: "shares groove language", strength: 0.45 },
      { from: "jazz-fusion", to: "rock", label: "electric crossover", strength: 0.45 },

      { from: "bb-king", to: "electric-blues", label: "defined voice in", strength: 0.95 },
      { from: "bb-king", to: "gibson-es-355-lucille", label: "signature guitar", strength: 0.95 },
      { from: "bb-king", to: "live-at-the-regal", label: "landmark release", strength: 0.78 },
      { from: "bb-king", to: "stevie-ray-vaughan", label: "influenced blues phrasing", strength: 0.66 },
      { from: "lead-belly", to: "blues", label: "roots repertoire", strength: 0.72 },
      { from: "lead-belly", to: "folk", label: "song tradition", strength: 0.74 },
      { from: "lead-belly", to: "twelve-string-sound", label: "twelve-string identity", strength: 0.72 },
      { from: "lead-belly", to: "national-resonator", label: "early acoustic volume world", strength: 0.48 },
      { from: "chuck-berry", to: "rock-and-roll", label: "guitar grammar", strength: 0.94 },
      { from: "chuck-berry", to: "gibson-es-355-lucille", label: "semi-hollow lineage", strength: 0.48 },
      { from: "elvis-presley", to: "rock-and-roll", label: "popularized", strength: 0.78 },
      { from: "elvis-presley", to: "country", label: "roots overlap", strength: 0.42 },

      { from: "jimi-hendrix", to: "psychedelic-rock", label: "expanded", strength: 0.96 },
      { from: "jimi-hendrix", to: "fender-stratocaster", label: "iconic instrument", strength: 0.96 },
      { from: "jimi-hendrix", to: "are-you-experienced", label: "debut statement", strength: 0.86 },
      { from: "jimi-hendrix", to: "whammy-bar", label: "expressive system", strength: 0.74 },
      { from: "jimi-hendrix", to: "distortion", label: "sonic expansion", strength: 0.82 },
      { from: "stevie-ray-vaughan", to: "electric-blues", label: "revived", strength: 0.86 },
      { from: "stevie-ray-vaughan", to: "fender-stratocaster", label: "main voice", strength: 0.9 },
      { from: "stevie-ray-vaughan", to: "texas-flood", label: "breakthrough", strength: 0.78 },
      { from: "stevie-ray-vaughan", to: "jimi-hendrix", label: "influence line", strength: 0.62 },
      { from: "john-mayer", to: "stevie-ray-vaughan", label: "modern blues influence", strength: 0.5 },
      { from: "john-mayer", to: "fender-stratocaster", label: "blues/pop instrument", strength: 0.62 },
      { from: "john-mayer", to: "electric-blues", label: "draws from", strength: 0.5 },

      { from: "eric-clapton", to: "the-yardbirds", label: "member", strength: 0.84 },
      { from: "eric-clapton", to: "cream", label: "member", strength: 0.86 },
      { from: "eric-clapton", to: "electric-blues", label: "blues-rock bridge", strength: 0.68 },
      { from: "eric-clapton", to: "gibson-les-paul", label: "classic era tone", strength: 0.62 },
      { from: "cream", to: "hard-rock", label: "loud trio bridge", strength: 0.54 },
      { from: "the-yardbirds", to: "jimmy-page", label: "member link", strength: 0.68 },
      { from: "the-yardbirds", to: "rock", label: "British blues-rock", strength: 0.56 },

      { from: "david-gilmour", to: "pink-floyd", label: "guitarist", strength: 0.95 },
      { from: "pink-floyd", to: "progressive-rock", label: "central band", strength: 0.9 },
      { from: "pink-floyd", to: "psychedelic-rock", label: "early identity", strength: 0.72 },
      { from: "david-gilmour", to: "fender-stratocaster", label: "signature tone", strength: 0.92 },
      { from: "pink-floyd", to: "dark-side-of-the-moon", label: "album", strength: 0.88 },
      { from: "david-gilmour", to: "dark-side-of-the-moon", label: "guitar voice on", strength: 0.64 },

      { from: "mark-knopfler", to: "dire-straits", label: "frontman", strength: 0.95 },
      { from: "dire-straits", to: "rock", label: "clean guitar rock", strength: 0.62 },
      { from: "mark-knopfler", to: "fingerpicking", label: "electric fingerstyle", strength: 0.88 },
      { from: "mark-knopfler", to: "fender-stratocaster", label: "clean tone link", strength: 0.7 },
      { from: "dire-straits", to: "brothers-in-arms", label: "album", strength: 0.86 },

      { from: "eddie-van-halen", to: "van-halen", label: "guitarist", strength: 0.96 },
      { from: "van-halen", to: "hard-rock", label: "arena hard rock", strength: 0.82 },
      { from: "eddie-van-halen", to: "frankenstrat", label: "built and played", strength: 0.96 },
      { from: "eddie-van-halen", to: "whammy-bar", label: "dive-bomb language", strength: 0.82 },
      { from: "eddie-van-halen", to: "van-halen-i", label: "breakthrough", strength: 0.86 },
      { from: "eddie-van-halen", to: "distortion", label: "brown sound", strength: 0.72 },

      { from: "frank-zappa", to: "jazz-fusion", label: "composed across", strength: 0.72 },
      { from: "frank-zappa", to: "rock", label: "rock framework", strength: 0.56 },
      { from: "frank-zappa", to: "gibson-sg", label: "stage guitar link", strength: 0.48 },
      { from: "johnny-marr", to: "the-smiths", label: "guitarist", strength: 0.94 },
      { from: "the-smiths", to: "punk", label: "post-punk aftermath", strength: 0.44 },
      { from: "johnny-marr", to: "rickenbacker-360-12", label: "jangly texture", strength: 0.7 },
      { from: "johnny-marr", to: "fender-jazzmaster", label: "offset guitar link", strength: 0.58 },

      { from: "randy-rhoads", to: "ozzy-osbourne", label: "guitarist", strength: 0.9 },
      { from: "randy-rhoads", to: "heavy-metal", label: "neoclassical edge", strength: 0.84 },
      { from: "randy-rhoads", to: "gibson-les-paul", label: "lead guitar link", strength: 0.52 },
      { from: "randy-rhoads", to: "gibson-flying-v", label: "stage shape link", strength: 0.62 },
      { from: "ozzy-osbourne", to: "heavy-metal", label: "solo metal context", strength: 0.68 },

      { from: "tony-iommi", to: "black-sabbath", label: "guitarist", strength: 0.96 },
      { from: "black-sabbath", to: "heavy-metal", label: "foundation", strength: 0.98 },
      { from: "tony-iommi", to: "gibson-sg", label: "iconic instrument", strength: 0.9 },
      { from: "black-sabbath", to: "paranoid", label: "album", strength: 0.86 },
      { from: "black-sabbath", to: "master-of-reality", label: "album", strength: 0.8 },
      { from: "tony-iommi", to: "distortion", label: "riff weight", strength: 0.78 },

      { from: "jimmy-page", to: "led-zeppelin", label: "guitarist / producer", strength: 0.96 },
      { from: "led-zeppelin", to: "hard-rock", label: "central band", strength: 0.9 },
      { from: "led-zeppelin", to: "blues", label: "roots source", strength: 0.58 },
      { from: "jimmy-page", to: "gibson-les-paul", label: "classic tone", strength: 0.86 },
      { from: "led-zeppelin", to: "led-zeppelin-iv", label: "album", strength: 0.86 },
      { from: "jimmy-page", to: "martin-d28", label: "acoustic color", strength: 0.42 },

      { from: "george-harrison", to: "the-beatles", label: "guitarist", strength: 0.96 },
      { from: "the-beatles", to: "rock", label: "central band", strength: 0.9 },
      { from: "the-beatles", to: "psychedelic-rock", label: "studio era", strength: 0.62 },
      { from: "the-beatles", to: "sgt-pepper", label: "album", strength: 0.88 },
      { from: "george-harrison", to: "rickenbacker-360-12", label: "twelve-string era", strength: 0.76 },
      { from: "george-harrison", to: "gretsch-6120", label: "early guitar color", strength: 0.48 },
      { from: "rickenbacker-360-12", to: "twelve-string-sound", label: "signature texture", strength: 0.9 },

      { from: "bob-dylan", to: "folk", label: "songwriting root", strength: 0.86 },
      { from: "bob-dylan", to: "rock", label: "electric turn", strength: 0.64 },
      { from: "bob-dylan", to: "highway-61-revisited", label: "electric-era album", strength: 0.9 },
      { from: "bob-dylan", to: "martin-d28", label: "acoustic tradition link", strength: 0.5 },
      { from: "johnny-cash", to: "country", label: "central figure", strength: 0.9 },
      { from: "johnny-cash", to: "at-folsom-prison", label: "live album", strength: 0.86 },
      { from: "johnny-cash", to: "martin-d28", label: "acoustic rhythm link", strength: 0.42 },
      { from: "willie-nelson", to: "country", label: "outlaw country voice", strength: 0.88 },
      { from: "willie-nelson", to: "trigger", label: "signature guitar", strength: 0.96 },
      { from: "willie-nelson", to: "fingerpicking", label: "nylon-string feel", strength: 0.72 },
      { from: "chet-atkins", to: "country", label: "Nashville guitar", strength: 0.82 },
      { from: "chet-atkins", to: "fingerpicking", label: "master style", strength: 0.92 },
      { from: "chet-atkins", to: "gretsch-6120", label: "signature association", strength: 0.88 },

      { from: "oystein-sunde", to: "norwegian-vise", label: "humor and songcraft", strength: 0.88 },
      { from: "oystein-sunde", to: "gitarkameratene", label: "member link", strength: 0.94 },
      { from: "oystein-sunde", to: "fingerpicking", label: "acoustic precision", strength: 0.72 },
      { from: "oystein-sunde", to: "banjo", label: "instrument link", strength: 0.74 },
      { from: "oystein-sunde", to: "kjekt-a-ha", label: "album", strength: 0.72 },
      { from: "gitarkameratene", to: "norwegian-vise", label: "group tradition", strength: 0.78 },

      { from: "james-hetfield", to: "metallica", label: "rhythm guitar / vocals", strength: 0.96 },
      { from: "metallica", to: "heavy-metal", label: "genre pillar", strength: 0.94 },
      { from: "james-hetfield", to: "esp-explorer-style", label: "stage guitar identity", strength: 0.82 },
      { from: "james-hetfield", to: "distortion", label: "tight rhythm tone", strength: 0.72 },
      { from: "prince", to: "funk", label: "groove core", strength: 0.86 },
      { from: "prince", to: "rock", label: "crossover guitar", strength: 0.62 },
      { from: "prince", to: "hohner-mad-cat", label: "signature stage guitar", strength: 0.84 },
      { from: "prince", to: "fender-telecaster", label: "Tele-style language", strength: 0.48 },

      { from: "fender", to: "fender-stratocaster", label: "made", strength: 0.98 },
      { from: "fender", to: "fender-telecaster", label: "made", strength: 0.98 },
      { from: "fender", to: "fender-jazzmaster", label: "made", strength: 0.96 },
      { from: "fender", to: "fender-jaguar", label: "made", strength: 0.96 },
      { from: "gibson", to: "gibson-les-paul", label: "made", strength: 0.98 },
      { from: "gibson", to: "gibson-sg", label: "made", strength: 0.98 },
      { from: "gibson", to: "gibson-es-355-lucille", label: "made", strength: 0.94 },
      { from: "gibson", to: "gibson-flying-v", label: "made", strength: 0.96 },
      { from: "gibson", to: "gibson-j45", label: "made", strength: 0.9 },
      { from: "martin", to: "martin-d28", label: "made", strength: 0.96 },
      { from: "martin", to: "trigger", label: "Martin N-20 base", strength: 0.82 },
      { from: "rickenbacker", to: "rickenbacker-360-12", label: "made", strength: 0.96 },
      { from: "gretsch", to: "gretsch-6120", label: "made", strength: 0.96 },
      { from: "esp", to: "esp-explorer-style", label: "made", strength: 0.9 },

      { from: "fender-stratocaster", to: "rock", label: "broad rock tool", strength: 0.52 },
      { from: "fender-stratocaster", to: "electric-blues", label: "blues lead voice", strength: 0.62 },
      { from: "fender-telecaster", to: "country", label: "bright attack", strength: 0.68 },
      { from: "fender-telecaster", to: "funk", label: "tight rhythm", strength: 0.48 },
      { from: "gibson-les-paul", to: "hard-rock", label: "sustain and humbuckers", strength: 0.72 },
      { from: "gibson-sg", to: "heavy-metal", label: "riff instrument", strength: 0.72 },
      { from: "gibson-es-355-lucille", to: "electric-blues", label: "singing semi-hollow", strength: 0.72 },
      { from: "gibson-flying-v", to: "heavy-metal", label: "stage shape", strength: 0.58 },
      { from: "martin-d28", to: "folk", label: "dreadnought tradition", strength: 0.72 },
      { from: "martin-d28", to: "country", label: "flatpicking link", strength: 0.68 },
      { from: "gibson-j45", to: "folk", label: "songwriter rhythm", strength: 0.62 },
      { from: "trigger", to: "country", label: "outlaw country identity", strength: 0.74 },
      { from: "national-resonator", to: "slide-guitar", label: "classic pairing", strength: 0.84 },
      { from: "slide-guitar", to: "blues", label: "core technique", strength: 0.82 },
      { from: "distortion", to: "hard-rock", label: "core sound", strength: 0.82 },
      { from: "distortion", to: "heavy-metal", label: "core sound", strength: 0.9 },
      { from: "whammy-bar", to: "fender-stratocaster", label: "built-in system", strength: 0.64 },
      { from: "fingerpicking", to: "folk", label: "common approach", strength: 0.76 },
      { from: "fingerpicking", to: "country", label: "common approach", strength: 0.7 },
    ],
  };
})();
